// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVWzPHSBRdiV1SIDIhjq-kfkRcl5vSCEM',
    appId: '1:942997457993:web:930843f58a214a71680398',
    messagingSenderId: '942997457993',
    projectId: 'izmir-etkinlik-project2',
    authDomain: 'izmir-etkinlik-project2.firebaseapp.com',
    storageBucket: 'izmir-etkinlik-project2.appspot.com',
    measurementId: 'G-C2D91WKCTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZhm61rfuMJZnmWLxi23DOno6svdposnQ',
    appId: '1:942997457993:android:610614b16afbbf10680398',
    messagingSenderId: '942997457993',
    projectId: 'izmir-etkinlik-project2',
    storageBucket: 'izmir-etkinlik-project2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaz310e7SaU27tVfWlx225SKCqeXqyb4w',
    appId: '1:942997457993:ios:0909d5b7ef61cbae680398',
    messagingSenderId: '942997457993',
    projectId: 'izmir-etkinlik-project2',
    storageBucket: 'izmir-etkinlik-project2.appspot.com',
    iosBundleId: 'com.example.flutterRestapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaz310e7SaU27tVfWlx225SKCqeXqyb4w',
    appId: '1:942997457993:ios:0909d5b7ef61cbae680398',
    messagingSenderId: '942997457993',
    projectId: 'izmir-etkinlik-project2',
    storageBucket: 'izmir-etkinlik-project2.appspot.com',
    iosBundleId: 'com.example.flutterRestapi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVWzPHSBRdiV1SIDIhjq-kfkRcl5vSCEM',
    appId: '1:942997457993:web:0fe8f92967624087680398',
    messagingSenderId: '942997457993',
    projectId: 'izmir-etkinlik-project2',
    authDomain: 'izmir-etkinlik-project2.firebaseapp.com',
    storageBucket: 'izmir-etkinlik-project2.appspot.com',
    measurementId: 'G-8V8JNFSMWX',
  );
}
